spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

jwt:
  issuer: eunho.moon@gmail.com
  secret_key: super_secret_key_sdkjfvnaretblak!W#dfkbnl234dsdfgsdfg+sdkmflakmgl1!!!-asdfasdfsaf
